### ISSUE TITLE
Syntax error when using with Typst 0.11

### ISSUE THREAD

**Issue by dnaka91** [JamesxX/valkyrie#1]
First of all, thanks for this great library!

With the recent Typst 0.11 a new `context` keyword was introduced and I think the `#import "context.typ": context` line conflicts with it.

This is probably fixable by simply renaming the import type to `ctx` or something similar.

**Comment by tingerrr** [comment]
Hey there, I just took over as a maintainer as James is busy with his PhD. I'll try getting a hotfix out in the next few days, but it won't be merged into the package repo until Monday as the Typst maintainers are on holiday until then.

**Comment by dnaka91** [comment]
Thanks for the quick update, much appreciated <3
